### ISSUE TITLE
Can't make transactions work

### ISSUE THREAD

**Issue by Diferno** [bbitgmbh/bbit.rdsdata.postgres#3]
Hi again guys,
sorry to bother again, but can't make transactions work at all.

Tryed different ways, but always get:

```json
query params {
   "database": "dev",
   "continueAfterTimeout": false,
   "sql": "start transaction",
   "includeResultMetadata": true
} BadRequestException: ERROR: DISCARD ALL cannot run inside a transaction block
```
Things I've tryed:

```javascript
const t = await sequelize.transaction()
```
```javascript
const client = new Client(`awsrds://....`);

await client.connect();
// const res = await client.query('select table_name from information_schema.tables where table_name = :name ', { name: 'pg_tables' });
const res = await client.query('start transaction');
```

Is there any option I have to set in the DB in order to make it work ????

_Please help me Obi Wan Kenoby, you're my last hope_

Thanks in advance!!

**Comment by jaggr2** [comment]
Sorry for the late reply. I didn't test transactions yet with sequelize, so the `start transaction` was not yet properly caught and redirected to the beginTransaction method of the AWS Data API. 

This is implemented now. Please let me know if transactions are now working in your case.

**Comment by jaggr2** [comment]
The tests are running smoothly now, so I'm gonna close this issue. If you find a bug, please reopen or create a new issue.
